board/urls.py
from django.urls import path, include
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('accounts/', include("django.contrib.auth.urls")),
    path('register/', views.register, name='register'),
    path('config/', views.config, name='config'),
    path('tabla/', views.tabla, name='tabla'),
    path('graficas/', views.graficas, name='graficas'),
    path('eliminar_instrumento/<int:pk>', views.eliminarInstrumento, name='eliminar_instrumento'),

]

''' 
urls for accounts/              
login
logout
password_change
password_change/done
password_reset
password_reset/done
reset/<uidb64>/<token>
reset/done
'''

sales/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from inventario import views
from sales import settings

router = routers.DefaultRouter()
router.register(r'productos', views.ProdcutoView, 'producto')
router.register(r'lineas', views.LineaView, 'linea')
router.register(r'notas', views.NotaView, 'nota')
# router.register(r'orders', views.OrderView, 'order')  #
# router.register(r'orders/(?P<order_id>\d+)', views.OrderView, 'order_detail')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inventario/', include('inventario.urls', namespace='invetario')),
    path('ordenes/', include('ordenes.urls', namespace='ordenes')),
    path('board/', include('board.urls', namespace='board')),
    path('api/', include(router.urls)),
]

#  urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

board/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import functools


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    follows = models.ManyToManyField("self", related_name="followed_by", symmetrical=False, blank=True)

    def __str__(self):
        return self.user.username


class Instrumento(models.Model):
    name = models.CharField(max_length=250)
    porcentaje_anual = models.FloatField(default=0)
    congelamiento_dias = models.FloatField(default=0)
    monto = models.FloatField(default=0)


    @property
    def gains_mes(self):
        return ((self.monto * self.porcentaje_anual) / 100)/12

    @property
    def gains_anual(self):
        return self.monto * (self.porcentaje_anual/100)


class GainDay(models.Model):
    date = models.CharField(max_length=250)
    mount = models.FloatField(default=0)


class Metricas(models.Model):
    instrumentos = models.ManyToManyField(Instrumento)
    profile = models.ForeignKey(Profile, related_name='metricas_profile', on_delete=models.CASCADE)

    @property
    def gains_mes_total(self):
        return functools.reduce(lambda acc, i: acc + i.gains_mes, self.instrumentos.all(), 0)

    @property
    def gains_anual_total(self):
        return functools.reduce(lambda acc, i : acc + i.gains_anual, self.instrumentos.all(), 0)

    @property
    def total_inversion_total(self):
        return functools.reduce(lambda acc, i: acc + i.monto, self.instrumentos.all(), 0)

    @property
    def prom_porcentaje_anual_total(self):
        return (self.gains_anual_total * 100) / self.total_inversion_total


# # #  Signals  # # #


@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        user_profile = Profile(user=instance)
        user_profile.save()


@receiver(post_save, sender=Profile)
def create_metricas(sender, instance, created, **kwargs):
    if created:
        Metricas.objects.create(profile=instance)

board/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import Instrumento, Metricas


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ("email",)


class InstrumentoForm(forms.ModelForm):
    class Meta:
        model = Instrumento
        fields = ['name', 'porcentaje_anual', 'congelamiento_dias', 'monto']




'''
class MetricaForm(forms.ModelForm):
    class Meta:
        model = Metricas
        fields = ['total_inversion', 'prom_porcentaje_anual', 'gains_mes', 'gains_anual', 'instrumentos', '']
'''

board/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib import messages
from django.urls import reverse
from .forms import CustomUserCreationForm
from django.contrib.auth import login
from .models import Profile, Instrumento, Metricas
from .forms import InstrumentoForm
from django.forms import modelformset_factory
import random


def dashboard(request):
    return render(request, "dashboard.html")


def config(request):
    return render(request, "config.html")


# genera un form editable para cada instrumento (formset)
@login_required
def tabla(request):
    user = request.user
    profile = get_object_or_404(Profile, user=user)
    metrica = Metricas.objects.filter(profile=profile).first()

    instrumentoFormSet = modelformset_factory(Instrumento, form=InstrumentoForm, extra=1)
    if request.method == 'POST':
        formset = instrumentoFormSet(request.POST, queryset=metrica.instrumentos.all())
        if formset.is_valid():
            new_instrumentos = formset.save(commit=False)
            for instrumento in new_instrumentos:
                if instrumento.pk:
                    instrumento.save()
                else:
                    instrumento.save()
                    metrica.instrumentos.add(instrumento)
            for instrumento in formset.deleted_objects:
                metrica.instrumentos.remove(instrumento)
            # metrica.instrumentos.set(new_instrumentos)
            return redirect('board:tabla')
        else:
            for form in formset:
                if form.errors:
                    print(form.errors)
            messages.error(request, "Hubo un error al guardar el instrumento")
            return redirect('board:tabla')

    else:
        formset = instrumentoFormSet(queryset=metrica.instrumentos.all())
    return render(request, "tabla.html", {'formset': formset, 'metrica': metrica})


@login_required
def graficas(request):
    user = request.user
    profile = get_object_or_404(Profile, user=user)
    metrica = Metricas.objects.filter(profile=profile).first()

    instrumentos = metrica.instrumentos.all()
    data_instrumentos = []

    for i in instrumentos:
        r, g, b = generate_random_color()  # Genera un color base
        border_color = f'rgba({r}, {g}, {b}, 1)'
        lighter_r, lighter_g, lighter_b = lighten_color(r, g, b)
        background_color = f'rgba({lighter_r}, {lighter_g}, {lighter_b}, 0.2)'

        data_instrumentos.append({
            'nombre': i.name,
            'porc_anual': i.porcentaje_anual,  # Suponiendo que tienes un campo 'rendimiento_anual'
            'congelamiento_dias': i.congelamiento_dias,
            'monto': i.monto,
            'gains_mes': i.gains_mes,
            'gains_anual': i.gains_anual,
            'backgroundColor': background_color,
            'borderColor': border_color,
        })

    return render(request, "metricas.html", {'data_instrumentos': data_instrumentos})


def eliminarInstrumento(request, pk):
    if request.method == 'POST':
        instrumento = get_object_or_404(Instrumento, pk=pk)
        instrumento.delete()
        return JsonResponse({'success': True})
    return JsonResponse({'success': False})


def register(request):
    if request.method == "GET":
        return render(
            request, "users/register.html",
            {"form": CustomUserCreationForm}
        )
    elif request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(reverse("board:dashboard"))


# utillery
def generate_random_color():
    r = random.randint(0, 255)
    g = random.randint(0, 255)
    b = random.randint(0, 255)
    return r, g, b


def lighten_color(r, g, b, factor=0.2):
    r = min(int(r + (255 - r) * factor), 255)
    g = min(int(g + (255 - g) * factor), 255)
    b = min(int(b + (255 - b) * factor), 255)
    return r, g, b

board/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/board.css' %}">
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div class="container fondo-oscuro texto-claro">
        <div class="green-mid text-white apptitle d-flex align-items-center">
            <h1 class="m-3 me-1 ms-4 align-self-baseline d-inline-block"> Dashboard </h1>
            <h6 class="m-3 ms-1 align-self-baseline d-inline-block text-super-white"> your cash balance</h6>
        </div>
        <div class="green-dark appmenu d-flex">
            <h6 class="col-sm-auto  m-1 mx-2 justfy-content"><a href="{% url 'board:config' %}" class="text-ultra-white text-decoration-none"> Configuracion </a></h6>
            <h6 class="col-sm-auto  m-1 mx-2 justfy-content"><a href="{% url 'board:tabla' %}" class="text-ultra-white text-decoration-none"> Lista </a></h6>
            <h6 class="col-sm-auto  m-1 mx-2 justfy-content"><a href="{% url 'board:graficas' %}" class="text-ultra-white text-decoration-none"> Graficas </a></h6>
            {% if user.is_authenticated %}
                <div class="dropdown col d-flex justify-content-end ">
                    <h6 class="dropdown-toggle text-ultra-white" id="dropdownMenuLink" data-toggle="dropdown"
                        aria-haspopup="true" data-bs-toggle="dropdown" aria-expanded="false" style="cursor: pointer;"> {{ user.username }}! </h6>

                    <div class="dropdown-menu " aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item col d-flex justify-content-end" href="#" onclick="document.getElementById('logout-form').submit();"> Cerrar sesion </a>
                        <a class="dropdown-item col d-flex justify-content-end" href="#" onclick="document.getElementById('password-change-form').submit();"> Cambiar contrasenia </a>
                    </div>
                </div>
                <form id="logout-form" action="{% url 'board:logout' %}" method="post" style="display: none;"> {% csrf_token %} </form>
                <form id="password-change-form" action="{% url 'board:password_change' %}" method="post" style="display: none;"> {% csrf_token %} </form>
            {% else %}
                <h6 class="col d-flex justify-content-end"> <a href=" {% url 'board:login' %} " class="text-white"> Login </a> </h6>
            {% endif %}
        </div>

        {% block content %}
        {% endblock %}
        
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>

board/templates/config.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <div class="card">
            <div class="card-body">
                <h3> Configura tu cuenta </h3>

                <h6> Estos valores solo se aplicaran cuando se sincronice por primera vez , y cuando por alguna razon
                se desactualice en refresh-token </h6>

                <h4> Token </h4>
                <input type="text" name="" id="">
                <h4> Refresh Token </h4>
                <input type="text" name="" id="">
                   <h4> Client ID </h4>
                <input type="text" name="" id="">
                   <h4> Client Secret </h4>
                <input type="text" name="" id="">
            </div>
        </div>
    </div>

{% endblock %}

</body>
</html>

board/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% extends 'base.html' %}

{% block content %}
<div>
    {% if user.is_authenticated %}
        <h4>Aqui se mostraran tus accesos {{ user.username }}</h4>
    {% else %}

    {% endif %}

</div>


{% endblock %}

</body>
</html>

board/templates/metricas.html
{% extends 'base.html' %}

{% block content %}
<script id="dinamic-script-metricas-chart" src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<div class="container d-flex text-center">
    <div class="d-flex flex-column justify-content-center">
        <h3>Distribucion</h3>
        <canvas id="myChart" width="300" height="300" class=""></canvas>
    </div>
    <div class="vr" style="width: 2px; margin:5px;"></div> <!-- Separador vertical -->
    <div class="d-flex flex-column align-items-center justify-content-center text-center w-100">
        <h3 class="mt-4">Tasas</h3>
        <canvas id="myChart2" width="500" height="500" class="m-2"></canvas>
        <hr style="margin:20px; border: 0.5px solid gray; width: 90%;">
        <h3 class="mt-4">Rendimiento en el tiempo (interes anual compuesto)</h3>
        <canvas id="myChart3" width="800" height="500" class="m-2"></canvas>
    </div>
</div>
<script id="dinamic-script-metricas">
    let instrumentosData = {{ data_instrumentos|safe }};
    let names = instrumentosData.map(i => i.nombre);
    let montos = instrumentosData.map(i => i.monto );
    let congelamientos = instrumentosData.map(i => i.congelamiento_dias );
    let porcs_anuales = instrumentosData.map(i => i.porc_anual );
    let gains_mensuales = instrumentosData.map(i => i.gains_mes );
    let gains_anuales = instrumentosData.map(i => i.gains_anual );
    let backgroundColors = instrumentosData.map(i => i.backgroundColor );
    let borderColors = instrumentosData.map(i => i.borderColor );

    let ctx = document.getElementById('myChart').getContext('2d');
    let myChart = new Chart(ctx, {
        type: 'pie',
        data: {
            labels: names,
            datasets: [{
                label: 'Monto invertido',
                data: montos,
                backgroundColor: backgroundColors,
                borderColor: borderColors,
                borderWidth: 1
            }]
        },
        options: {
           responsive: false, // Desactiva la respuesta para respetar las dimensiones
           maintainAspectRatio: false, // Evita mantener la relación de aspecto
           plugins: {
              legend: {
                position: 'top',
              },
              tooltip: {
                callbacks: {
                  label: function(tooltipItem) {
                    return '$' + tooltipItem.raw ;
                  }
                }
              }
           }
        }
    });

    var ctx2 = document.getElementById('myChart2').getContext('2d');
    var myChart2 = new Chart(ctx2, {
        type: 'bar',
        data: {
            labels: names, //no importa
            datasets: [{
                label: 'Rendimiento Anual',
                data: porcs_anuales,
                backgroundColor: backgroundColors,
                borderColor: borderColors,
                borderWidth: 1
            }]
        },
        options: {
            responsive: false, // Desactiva la respuesta para respetar las dimensiones
           maintainAspectRatio: false, // Evita mantener la relación de aspecto
            plugins: {
                legend: {
                    display: false  // Esto oculta la leyenda,
                },
                tooltip: {
                    callbacks: {
                        label: function(tooltipItem) {
                            return tooltipItem.label + ': ' + tooltipItem.raw + '%';
                        }
                    }
                }
            },
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    });


    // Acumulacion en 10 anios
    let montosAcumulados = montos.map((montoInicial, index) => {
        let montosAnio = [];
        let montoActual = montoInicial;

        for (let i = 0; i < 20; i++) {
            montoActual += montoActual * (porcs_anuales[index]/100);
            montosAnio.push(montoActual.toFixed(2));
        }

        return montosAnio;
    });

    // Preparar los datos para el gráfico
    let datasets = montosAcumulados.map((montosAnio, index) => {
        return {
            label: names[index],
            data: montosAnio,
            backgroundColor: backgroundColors[index],
            borderColor: borderColors[index],
            fill: false,
            borderWidth: 2
        };
    });
     console.log(datasets)

    let ctx3 = document.getElementById('myChart3').getContext('2d');
    let myChart3 = new Chart(ctx3, {
        type: 'line',
        data: {
            labels: Array.from({length: 20}, (_, i) => `Año ${i + 1}`),
            datasets: datasets
        },
        options: {
            responsive: false,
            maintainAspectRatio: false,
            plugins: {
                legend: {
                    position: 'top',
                },
                tooltip: {
                    callbacks: {
                        label: function(tooltipItem) {
                            return tooltipItem.dataset.label + ': $' + tooltipItem.raw;
                        }
                    }
                }
            },
            scales: {
                y: {
                    title: {
                        display: true,
                        text: 'Monto Acumulado ($)'
                    },
                    beginAtZero: true
                }
            }
        }
    });
</script>

{% endblock %}

board/templates/tabla.html
{% extends 'base.html' %}

{% block content %}
{% load humanize %}
<script id="dinamic-script-tabla">
    function eliminarInstrumento(instrumentoId){
        if (confirm("¿Estás seguro de que deseas eliminar este instrumento?")) {
            fetch(`{% url 'board:eliminar_instrumento' 0 %}`.replace('0', instrumentoId), {
                method: 'POST',
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}',
                },
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    document.getElementById(`instrumento-${instrumentoId}`).remove();
                } else {
                    alert("No se pudo eliminar el instrumento.");
                }
            })
            .catch(error => {
                console.error('Error:', error);
                alert("Hubo un error al eliminar el instrumento.");
            });
        }
    }
</script>

<div class="mt-4">
    <div class="d-flex flex-column text-center">
        <h3 class="mb-1 text-super-white"> Resumen </h3>
        {% load humanize %}
        <div class="container d-flex align-items-center justify-content-center">
            <div class="card m-3 fondo-oscuro-c"><div class="card-body">
                <h5> Total </h5>
                <h4> $ {{ metrica.total_inversion_total|floatformat:2|intcomma  }} </h4>
            </div></div>
            <div class="card m-3 fondo-oscuro-c"><div class="card-body">
                <h5> Gains mensual</h5>
                <h4> $ {{ metrica.gains_mes_total|floatformat:2|intcomma }} </h4>
            </div></div>
            <div class="card  m-3 fondo-oscuro-c"><div class="card-body">
                <h5> Gains 365</h5>
                <h4> $ {{ metrica.gains_anual_total|floatformat:2|intcomma }} </h4>
            </div></div>
            <div class="card  m-3 fondo-oscuro-c"><div class="card-body">
                <h5> Prom % 365</h5>
                <h4> $ {{ metrica.prom_porcentaje_anual_total|floatformat:2|intcomma }} </h4>
            </div></div>
        </div>
    </div>

    <form method="post" action="{% url 'board:tabla' %}" class="my-3 text-center">
        {% csrf_token %}
        {{ formset.management_form }}
        <table class="table fondo-oscuro-b texto-claro" >
            <tr >
              <th scope="col" >Instrumento</th>
              <th scope="col" >% Anual</th>
              <th scope="col" >Congelado dias</th>
              <th scope="col" >Monto</th>
              <th scope="col" >Gains mensual</th>
              <th scope="col" >Gains anual</th>
              <th scope="col" >Delete</th>
            </tr>

            {% for form in formset %}
                {% for hidden in form.hidden_fields %}
                     {{ hidden }}
                {% endfor %}
                <div class="hidden">{{ form.id }}</div>
                <tr scope="row" id="instrumento-{{ form.instance.id }}">
                    <td class="input_form">{{form.name}}</td>
                    <td class="input_form"> {{form.porcentaje_anual}}</td>
                    <td class="input_form">{{form.congelamiento_dias}}</td>
                    <td class="input_form">{{form.monto}}</td>
                    <td class="input_form">{{form.instance.gains_mes}}</td>
                    <td class="input_form">{{form.instance.gains_anual}}</td>
                    <td class="input_form"><button type="button" class="btn btn-danger" onclick='eliminarInstrumento({{ form.instance.id }})'> X </button></td>
                </tr>
            {% endfor %}

        </table>
        <button type="submit" class="btn fondoPrincipal text-super-white"> Guardar cambios </button>

    </form >

</div>

{% endblock %}